/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e2e2e2",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#0b1d2d",
        "on-tertiary-container": "#586166",
        "on-secondary-fixed-variant": "#38485a",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f9f9f9",
        "on-primary-fixed-variant": "#0f4c64",
        "surface-dim": "#dadada",
        "primary-fixed": "#c1e8ff",
        "on-background": "#1a1c1c",
        "surface": "#f9f9f9",
        "secondary-fixed-dim": "#b7c8de",
        "error": "#ba1a1a",
        "surface-container": "#eeeeee",
        "secondary": "#4f6073",
        "on-error-container": "#93000a",
        "outline": "#71787d",
        "surface-tint": "#2f647d",
        "on-primary-container": "#30667e",
        "inverse-primary": "#9acdea",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#d2e4fb",
        "on-surface-variant": "#41484c",
        "background": "#f9f9f9",
        "tertiary-fixed": "#dbe4ea",
        "on-tertiary-fixed": "#141d21",
        "surface-container-high": "#e8e8e8",
        "outline-variant": "#c0c7cd",
        "surface-container-highest": "#e2e2e2",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#9acdea",
        "on-surface": "#1a1c1c",
        "on-tertiary-fixed-variant": "#3f484d",
        "tertiary": "#576065",
        "on-primary-fixed": "#001e2b",
        "inverse-on-surface": "#f0f1f1",
        "inverse-surface": "#2f3131",
        "secondary-fixed": "#d2e4fb",
        "tertiary-container": "#d3dce2",
        "primary-container": "#aee2ff",
        "error-container": "#ffdad6",
        "surface-container-low": "#f3f3f4",
        "on-secondary-container": "#556679",
        "tertiary-fixed-dim": "#bfc8ce",
        "primary": "#2f647d"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "64px",
        "gutter": "24px",
        "base": "8px",
        "container-max": "1280px",
        "section-gap": "120px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "sans-serif"],
        "label-caps": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-lg-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"]
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "display-lg-mobile": ["40px", { lineHeight: "48px", letterSpacing: "0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "40px", letterSpacing: "0.01em", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      },
      boxShadow: {
        'sky-glow': '0 32px 64px -12px rgba(26, 43, 60, 0.05)',
        'soft-float': '0 20px 40px -15px rgba(47, 100, 125, 0.12)',
        'card-hover': '0 24px 48px -10px rgba(47, 100, 125, 0.15)',
      }
    },
  },
  plugins: [],
}
